services:
    api:
        image: api
        restart: unless-stopped
        build: .
        ports:
            - "${PORT:-3000}:${PORT:-3000}"

networks:
  default:
    name: docker-example
    external: true