services:
    api:
        container_name: api
        image: api
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: base
        ports:
            - "${PORT:-3000}:${PORT:-3000}"
        networks:
            - docker-example
networks:
  docker-example:
    name: docker-example
    external: true